import {createClient} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.111.0/+esm";
const supabase=createClient("https://tjpisutgkiehskucfabb.supabase.co","sb_publishable_9FBaLHlEJadn2g5VYyBzMQ_AL2rq1G2",{db:{schema:"hgs_customers"}});
const CHANNELS=[{id:"channel_airtel_money",name:"Airtel Money"},{id:"channel_halopesa",name:"HaloPesa"},{id:"channel_mpesa",name:"M-Pesa"},{id:"channel_mixx_by_yas",name:"Mixx by Yas"},{id:"channel_nmb",name:"NMB"}];
let txns=[],relationship=null,partner="Denis",currentPage="home",previousPage="home",selectedTxnId=null;
let filters={status:"all",direction:"all",channel:"all",sort:"newest",search:""};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const fmt=n=>`TZS ${Math.abs(Number(n)||0).toLocaleString("en-US",{maximumFractionDigits:2})}`;
const signed=n=>`${Number(n)<0?"-":""}${fmt(n)}`;
const effect=t=>t.status==="done"?(t.direction==="withdraw"?+Number(t.amount):-Number(t.amount)):0;
const peffect=t=>t.status==="pending"?(t.direction==="withdraw"?+Number(t.amount):-Number(t.amount)):0;
const channelName=id=>CHANNELS.find(c=>c.id===id)?.name||id||"—";
const txnDate=t=>new Date(t.effective_at||t.created_at);
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function meaning(v,name=partner){return v>0?`Office owes ${name}`:v<0?`${name} owes Office`:"Balanced"}
function totals(){const done=txns.filter(t=>t.status==="done"),pending=txns.filter(t=>t.status==="pending");return{done,pending,bal:done.reduce((a,t)=>a+effect(t),0),ds:done.filter(t=>t.direction==="send").reduce((a,t)=>a+Number(t.amount),0),dw:done.filter(t=>t.direction==="withdraw").reduce((a,t)=>a+Number(t.amount),0),pn:pending.reduce((a,t)=>a+peffect(t),0)}}
function running(){let b=0,m=new Map();txns.filter(t=>t.status==="done").sort((a,b)=>txnDate(a)-txnDate(b)).forEach(t=>{b+=effect(t);m.set(t.id,b)});return m}
function moneyClass(v){return Number(v)<0?"negative":"positive"}
function card(t){return `<button class="txn-card ${t.direction}" data-open-txn="${t.id}"><div><b class="name">${esc(t.name)}</b><small class="meta">${esc(channelName(t.channel_id))} · ${txnDate(t).toLocaleString()}</small></div><div class="right"><small class="direction">${t.direction.toUpperCase()}</small><div class="amount">${t.direction==="send"?"-":"+"}${fmt(t.amount)}</div><span class="pill ${t.status}">${t.status.toUpperCase()}</span></div></button>`}
function customerData(){const map=new Map();txns.forEach(t=>{const key=(t.name||"").trim();if(!key)return;let c=map.get(key)||{name:key,balance:0,latest:null,channels:new Map()};if(t.status==="done")c.balance+=effect(t);c.channels.set(t.channel_id,(c.channels.get(t.channel_id)||0)+1);if(!c.latest||txnDate(t)>txnDate(c.latest))c.latest=t;map.set(key,c)});return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function renderCustomers(){const q=$("#customerSearch").value.trim().toLowerCase();const rows=customerData().filter(c=>!q||c.name.toLowerCase().includes(q)||channelName(c.latest?.channel_id).toLowerCase().includes(q));$("#customerList").innerHTML=rows.length?rows.map(c=>`<button class="customer-row" data-customer="${esc(c.name)}"><span class="initial">${esc(c.name[0]?.toUpperCase()||"?")}</span><span><b>${esc(c.name)}</b><small>${esc(channelName(c.latest?.channel_id))}</small></span><span class="customer-balance ${moneyClass(c.balance)}"><small>${esc(meaning(c.balance,c.name))}</small><strong>${signed(c.balance)}</strong></span><span>›</span></button>`).join(""):`<div class="empty">No matching customers.</div>`;$$('[data-customer]').forEach(b=>b.onclick=()=>selectCustomer(b.dataset.customer))}
function filteredTxns(){let a=[...txns];if(filters.status!=="all")a=a.filter(t=>t.status===filters.status);if(filters.direction!=="all")a=a.filter(t=>t.direction===filters.direction);if(filters.channel!=="all")a=a.filter(t=>t.channel_id===filters.channel);if(filters.search){const q=filters.search.toLowerCase();a=a.filter(t=>(t.name||"").toLowerCase().includes(q)||channelName(t.channel_id).toLowerCase().includes(q)||String(t.amount).includes(q))}a.sort((x,y)=>filters.sort==="oldest"?txnDate(x)-txnDate(y):filters.sort==="highest"?Number(y.amount)-Number(x.amount):filters.sort==="lowest"?Number(x.amount)-Number(y.amount):txnDate(y)-txnDate(x));return a}
function render(){const t=totals();$("#partnerName").textContent=partner;const hour=new Date().getHours(),day=hour<12?"morning":hour<18?"afternoon":"evening";$("#greeting").textContent=`Good ${day}, ${partner} 👋`;$("#balance").textContent=signed(t.bal);$("#balanceMeaning").textContent=meaning(t.bal);$("#hero").classList.toggle("negative",t.bal<0);$("#doneSend").textContent=fmt(t.ds);$("#doneWithdraw").textContent=fmt(t.dw);$("#pendingCountHome").textContent=`${t.pending.length} pending transaction${t.pending.length===1?"":"s"}`;$("#pendingHome").textContent=signed(t.pn);$("#pendingHome").className=moneyClass(t.pn);$("#pendingNet").textContent=signed(t.pn);$("#pendingMeaning").textContent=t.pn?meaning(t.pn):"No pending effect";$("#pendingSummary").classList.remove("negative","positive");$("#pendingSummary").classList.add(moneyClass(t.pn));$("#pendingTitle").textContent=`Pending (${t.pending.length})`;const recent=[...txns].sort((a,b)=>txnDate(b)-txnDate(a)).slice(0,5);$("#recentList").innerHTML=recent.length?recent.map(card).join(""):`<div class="empty">No transactions yet.</div>`;$("#pendingList").innerHTML=t.pending.length?[...t.pending].sort((a,b)=>txnDate(b)-txnDate(a)).map(card).join(""):`<div class="empty">No pending transactions.</div>`;const list=filteredTxns();$("#transactionList").innerHTML=list.length?list.map(card).join(""):`<div class="empty">No transactions match this view.</div>`;$("#resultCount").textContent=`${list.length} transaction${list.length===1?"":"s"}`;const hasFilter=filters.status!=="all"||filters.direction!=="all"||filters.channel!=="all"||filters.sort!=="newest"||filters.search;$("#clearFilters").classList.toggle("hidden",!hasFilter);wireCards();renderCustomers();if(selectedTxnId)renderDetail()}
function wireCards(){$$('[data-open-txn]').forEach(b=>b.onclick=()=>openDetail(b.dataset.openTxn))}
function renderDetail(){const t=txns.find(x=>x.id===selectedTxnId);if(!t)return;const r=running(),b=r.get(t.id);$("#detailHero").className=`detail-hero ${t.direction}`;$("#detailHero").innerHTML=`<div class="row"><div><h2>${esc(t.name)}</h2><div class="channel">${esc(channelName(t.channel_id))}</div></div><div><div class="dir">${t.direction.toUpperCase()}</div><div class="amount">${t.direction==="send"?"-":"+"}${fmt(t.amount)}</div><span class="pill ${t.status}">${t.status.toUpperCase()}</span></div></div>`;const balanceAfter=t.status==="done"?signed(b):"Not affected";$("#detailFacts").innerHTML=[["Direction",t.direction==="send"?"Send · He owes Office":"Withdraw · Office owes him"],["Channel",channelName(t.channel_id)],["Amount",`${t.direction==="send"?"-":"+"}${fmt(t.amount)}`],["Status",t.status.toUpperCase()],["Created",txnDate(t).toLocaleString()],["Balance after",balanceAfter]].map(([k,v],i)=>`<div class="fact"><span>${esc(k)}</span><span class="${i===2||i===5?`money-value ${t.direction==="send"?"negative":""}`:""}">${esc(v)}</span></div>`).join("");$("#detailNote").classList.toggle("hidden",!t.note);$("#detailNote").textContent=t.note?`Note: ${t.note}`:"";$("#toggleStatus").textContent=t.status==="pending"?"✓ Mark Done":"◷ Move to Pending"}
function go(n,{remember=true}={}){if(remember&&currentPage!==n)previousPage=currentPage;currentPage=n;$$('.page').forEach(x=>x.classList.add('hidden'));$('#'+n).classList.remove('hidden');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.go===n));$('#fab').classList.toggle('hidden',["add","detail","filterPage","customers"].includes(n));window.scrollTo({top:0,behavior:"smooth"})}
function back(){go(previousPage||"home",{remember:false})}
function openForm(t=null){$("#txnForm").reset();$("#txnId").value=t?.id||"";$("#formTitle").textContent=t?"Edit Transaction":"Add Transaction";$("#name").value=t?.name||"";$("#customerButtonText").textContent=t?.name||"Select or search customer";$("#customerButtonText").style.color=t?.name?"#172119":"";$("#amount").value=t?Number(t.amount).toLocaleString():"";$("#channel").value=t?.channel_id||CHANNELS[0].id;if(t)$(`input[name=direction][value=${t.direction}]`).checked=true;setStatusChoice(t?.status||"pending");$("#note").value=t?.note||"";go("add");preview()}
function setStatusChoice(v){$("#status").value=v;$$('[data-status-choice]').forEach(b=>b.classList.toggle("active",b.dataset.statusChoice===v));preview()}
function selectCustomer(name){$("#name").value=name;$("#customerButtonText").textContent=name;$("#customerButtonText").style.color="#172119";go("add",{remember:false})}
const parse=v=>Number(String(v).replace(/,/g,""));
function preview(){const a=parse($("#amount").value)||0,s=$("#status").value,d=$('input[name=direction]:checked')?.value;if(s==="pending"||!d){$("#preview").textContent="Pending: not included in current balance.";return}let cur=totals().bal,old=txns.find(t=>t.id===$("#txnId").value);if(old?.status==="done")cur-=effect(old);const n=cur+(d==="withdraw"?a:-a);$("#preview").textContent=`Balance after save: ${signed(n)} · ${meaning(n)}`}
async function saveTxn(e){e.preventDefault();const id=$("#txnId").value,a=parse($("#amount").value),d=$('input[name=direction]:checked')?.value,name=$("#name").value.trim();if(!name)return toast("Select a customer.");if(!d||!a||a<=0)return toast("Enter amount and direction.");const payload={relationship_id:relationship.id,name,amount:a,channel_id:$("#channel").value,direction:d,status:$("#status").value,note:$("#note").value.trim()||null};const q=id?supabase.from("transactions").update(payload).eq("id",id):supabase.from("transactions").insert(payload);const{error}=await q;if(error)return toast(error.message);toast(id?"Transaction updated":"Transaction saved");await load();go(id?"detail":"transactions",{remember:false});if(id)selectedTxnId=id}
async function setTxnStatus(){const t=txns.find(x=>x.id===selectedTxnId);if(!t)return;const status=t.status==="pending"?"done":"pending";const{error}=await supabase.from("transactions").update({status}).eq("id",t.id);if(error)return toast(error.message);toast(status==="done"?"Marked Done":"Moved to Pending");await load();renderDetail()}
async function delTxn(){const t=txns.find(x=>x.id===selectedTxnId);if(!t||!confirm("Delete this transaction? Balances will recalculate."))return;const{error}=await supabase.from("transactions").delete().eq("id",t.id);if(error)return toast(error.message);toast("Transaction deleted");selectedTxnId=null;await load();go("transactions",{remember:false})}
function openDetail(id){selectedTxnId=id;renderDetail();go("detail")}
async function bootstrap(){const{data:m,error:e1}=await supabase.from("relationship_members").select("*").eq("active",true).limit(1).maybeSingle();if(e1||!m)return toast(e1?.message||"No active relationship membership found.");const{data:r,error:e2}=await supabase.from("relationships").select("*").eq("id",m.relationship_id).single();if(e2)return toast(e2.message);relationship=r;const{data:people}=await supabase.from("people").select("id,display_name").in("id",[r.office_person_id,r.partner_person_id]);partner=people?.find(p=>p.id===r.partner_person_id)?.display_name||"Denis";await load()}
async function load(){const{data,error}=await supabase.from("transactions").select("*").eq("relationship_id",relationship.id).order("created_at",{ascending:false});if(error)return toast(error.message);txns=data||[];render()}
function hideSplash(){setTimeout(()=>{$("#splash").classList.add("fade");setTimeout(()=>$("#splash").classList.add("hidden"),380)},650)}
$("#channel").innerHTML=CHANNELS.map(c=>`<option value="${c.id}">${c.name}</option>`).join("");$("#channelFilter").innerHTML+=CHANNELS.map(c=>`<option value="${c.id}">${c.name}</option>`).join("");
$("#loginForm").onsubmit=async e=>{e.preventDefault();const{error}=await supabase.auth.signInWithPassword({email:$("#email").value.trim(),password:$("#password").value});if(error)toast(error.message)};
$("#logout").onclick=()=>$("#moreSheet").classList.remove("hidden");$("#moreLogout").onclick=()=>supabase.auth.signOut();
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-back]').forEach(b=>b.onclick=back);$("#fab").onclick=()=>openForm();$("#moreAdd").onclick=()=>{$("#moreSheet").classList.add("hidden");openForm()};$("#moreBtn").onclick=()=>$("#moreSheet").classList.remove("hidden");$("#closeMore").onclick=()=>$("#moreSheet").classList.add("hidden");$$('[data-more-go]').forEach(b=>b.onclick=()=>{$("#moreSheet").classList.add("hidden");go(b.dataset.moreGo)});
$("#txnForm").onsubmit=saveTxn;$("#customerButton").onclick=()=>{renderCustomers();go("customers")};$("#customerSearch").oninput=renderCustomers;$("#newCustomer").onclick=()=>$("#newCustomerBox").classList.toggle("hidden");$("#useNewCustomer").onclick=()=>{const n=$("#newCustomerName").value.trim();if(!n)return toast("Enter customer name.");selectCustomer(n);$("#newCustomerName").value="";$("#newCustomerBox").classList.add("hidden")};
["amount"].forEach(id=>$("#"+id).oninput=preview);$$('input[name=direction]').forEach(x=>x.onchange=preview);$$('[data-status-choice]').forEach(b=>b.onclick=()=>setStatusChoice(b.dataset.statusChoice));
$("#editTxn").onclick=()=>openForm(txns.find(t=>t.id===selectedTxnId));$("#toggleStatus").onclick=setTxnStatus;$("#deleteTxn").onclick=delTxn;
$("#txnSearch").oninput=e=>{filters.search=e.target.value.trim();render()};$$('[data-quick]').forEach(b=>b.onclick=()=>{filters.status=b.dataset.quick;$$('[data-quick]').forEach(x=>x.classList.toggle("active",x===b));render()});$("#openFilter").onclick=()=>go("filterPage");
$$('[data-filter-status]').forEach(b=>b.onclick=()=>{$$('[data-filter-status]').forEach(x=>x.classList.remove("active"));b.classList.add("active")});$$('[data-filter-direction]').forEach(b=>b.onclick=()=>{$$('[data-filter-direction]').forEach(x=>x.classList.remove("active"));b.classList.add("active")});
$("#applyFilter").onclick=()=>{filters.status=$('[data-filter-status].active').dataset.filterStatus;filters.direction=$('[data-filter-direction].active').dataset.filterDirection;filters.channel=$("#channelFilter").value;filters.sort=$("#sortFilter").value;$$('[data-quick]').forEach(x=>x.classList.toggle("active",x.dataset.quick===filters.status));go("transactions",{remember:false});render()};
$("#clearFilters").onclick=()=>{filters={status:"all",direction:"all",channel:"all",sort:"newest",search:""};$("#txnSearch").value="";$$('[data-quick]').forEach(x=>x.classList.toggle("active",x.dataset.quick==="all"));$$('[data-filter-status]').forEach(x=>x.classList.toggle("active",x.dataset.filterStatus==="all"));$$('[data-filter-direction]').forEach(x=>x.classList.toggle("active",x.dataset.filterDirection==="all"));$("#channelFilter").value="all";$("#sortFilter").value="newest";render()};
supabase.auth.onAuthStateChange(async(_e,s)=>{const on=!!s;$("#auth").classList.toggle("hidden",on);$("#app").classList.toggle("hidden",!on);if(on)await bootstrap()});
const{data:{session}}=await supabase.auth.getSession();if(session){$("#auth").classList.add("hidden");$("#app").classList.remove("hidden");await bootstrap()}else $("#auth").classList.remove("hidden");hideSplash();
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));